#ifndef NATALIA_DEVICE_BOARD_PINS_H
#define NATALIA_DEVICE_BOARD_PINS_H

#include <stdint.h>

#include "stm32l496xx.h"

#define BOARD_PIN_UNUSED_PORT   ((GPIO_TypeDef *)0)
#define BOARD_PIN_UNUSED_NUMBER (0xFFU)
#define BOARD_AF_NONE           (0xFFU)

typedef struct {
    GPIO_TypeDef *port;
    uint8_t pin;
    uint8_t af;
} BoardPinDesc;

typedef enum {
    BOARD_PIN_QSPI_BK1_NCS = 0,
    BOARD_PIN_QSPI_BK1_IO0,
    BOARD_PIN_QSPI_BK1_IO1,
    BOARD_PIN_QSPI_BK1_IO2,
    BOARD_PIN_QSPI_BK1_IO3,
    BOARD_PIN_QSPI_BK1_CLK,

    BOARD_PIN_QSPI_BK2_NCS,
    BOARD_PIN_QSPI_BK2_IO0,
    BOARD_PIN_QSPI_BK2_IO1,
    BOARD_PIN_QSPI_BK2_IO2,
    BOARD_PIN_QSPI_BK2_IO3,
    BOARD_PIN_QSPI_BK2_CLK,

    BOARD_PIN_SPI1_NSS,
    BOARD_PIN_SPI1_SCK,
    BOARD_PIN_SPI1_MISO,
    BOARD_PIN_SPI1_MOSI,

    BOARD_PIN_SPI3_NSS,
    BOARD_PIN_SPI3_SCK,
    BOARD_PIN_SPI3_MISO,
    BOARD_PIN_SPI3_MOSI,

    BOARD_PIN_I2C1_SCL,
    BOARD_PIN_I2C1_SDA,

    BOARD_PIN_I2C2_SCL,
    BOARD_PIN_I2C2_SDA,

    BOARD_PIN_I2C3_SCL,
    BOARD_PIN_I2C3_SDA,

    BOARD_PIN_USB_DM,
    BOARD_PIN_USB_DP,

    BOARD_PIN_CAN1_RX,
    BOARD_PIN_CAN1_TX,
    BOARD_PIN_CAN2_RX,
    BOARD_PIN_CAN2_TX,

    BOARD_PIN_RTC_OUT,
    BOARD_PIN_ADC12_IN5,

    BOARD_PIN_USART2_RX,
    BOARD_PIN_USART2_TX,

    BOARD_PIN_PED_REG_DATA0,
    BOARD_PIN_PED_REG_DATA1,
    BOARD_PIN_PED_REG_DATA2,
    BOARD_PIN_PED_REG_DATA3,
    BOARD_PIN_PED_REG_DATA4,
    BOARD_PIN_PED_REG_DATA5,
    BOARD_PIN_PED_REG_DATA6,
    BOARD_PIN_PED_REG_DATA7,
    BOARD_PIN_PED_REG_DATA8,
    BOARD_PIN_PED_REG_DATA9,
    BOARD_PIN_PED_REG_DATA10,
    BOARD_PIN_PED_REG_DATA11,
    BOARD_PIN_PED_REG_DATA12,
    BOARD_PIN_PED_REG_DATA13,
    BOARD_PIN_PED_REG_DATA14,
    BOARD_PIN_PED_REG_DATA15,

    BOARD_PIN_PED_REG_ADDR0,
    BOARD_PIN_PED_REG_ADDR1,
    BOARD_PIN_PED_REG_ADDR2,
    BOARD_PIN_PED_REG_ADDR3,
    BOARD_PIN_PED_REG_ADDR4,
    BOARD_PIN_PED_REG_ADDR5,
    BOARD_PIN_PED_REG_ADDR6,
    BOARD_PIN_PED_REG_ADDR7,

    BOARD_PIN_PED_REG_DIR,
    BOARD_PIN_PED_REG_WRCLK,
    BOARD_PIN_PED_REG_READY,

    BOARD_PIN_PU_CAN1_SHDN,
    BOARD_PIN_PU_CAN1_S,
    BOARD_PIN_PU_CAN2_SHDN,
    BOARD_PIN_PU_CAN2_S,

    BOARD_PIN_PU_NAND1_PS,
    BOARD_PIN_PU_NAND1_PSON,
    BOARD_PIN_PU_NAND2_PS,
    BOARD_PIN_PU_NAND2_PSON,

    BOARD_PIN_PU_PED_PS,
    BOARD_PIN_PU_USB_VBUS,

    BOARD_PIN_PED_TG,
    BOARD_PIN_PED_TGRES,
    BOARD_PIN_PED_INHIBIT,
    BOARD_PIN_PED_SLEEP,
    BOARD_PIN_PED_PSON,

    BOARD_PIN_DEBUG_UART_TX,
    BOARD_PIN_DEBUG_UART_RX,

    BOARD_PIN_USART1_TX,
    BOARD_PIN_USART1_RX,
    BOARD_PIN_USART1_CTS,
    BOARD_PIN_USART1_RTS,

    BOARD_PIN_PU_FTDI_PS,
    BOARD_PIN_PU_FTDI_PSON,
    BOARD_PIN_PU_FTDI_RES,

    BOARD_PIN_COUNT
} BoardPinId;

const BoardPinDesc *board_pin_get(BoardPinId id);

#endif /* NATALIA_DEVICE_BOARD_PINS_H */