#include "board_pins.h"

#define PIN_DESC(port_name, pin_number, af_number) \
    { GPIO##port_name, (uint8_t)(pin_number), (uint8_t)(af_number) }

#define PIN_UNUSED \
    { BOARD_PIN_UNUSED_PORT, BOARD_PIN_UNUSED_NUMBER, BOARD_AF_NONE }

static const BoardPinDesc board_pins[BOARD_PIN_COUNT] = {
    [BOARD_PIN_QSPI_BK1_NCS] = PIN_DESC(E, 11, BOARD_AF_NONE),
    [BOARD_PIN_QSPI_BK1_IO0] = PIN_DESC(E, 12, BOARD_AF_NONE),
    [BOARD_PIN_QSPI_BK1_IO1] = PIN_DESC(E, 13, BOARD_AF_NONE),
    [BOARD_PIN_QSPI_BK1_IO2] = PIN_DESC(E, 14, BOARD_AF_NONE),
    [BOARD_PIN_QSPI_BK1_IO3] = PIN_DESC(E, 15, BOARD_AF_NONE),
    [BOARD_PIN_QSPI_CLK] = PIN_DESC(E, 10, BOARD_AF_NONE),

    [BOARD_PIN_QSPI_BK2_NCS] = PIN_DESC(C, 11, BOARD_AF_NONE),
    [BOARD_PIN_QSPI_BK2_IO0] = PIN_DESC(C, 1, BOARD_AF_NONE),
    [BOARD_PIN_QSPI_BK2_IO1] = PIN_DESC(C, 2, BOARD_AF_NONE),
    [BOARD_PIN_QSPI_BK2_IO2] = PIN_DESC(C, 3, BOARD_AF_NONE),
    [BOARD_PIN_QSPI_BK2_IO3] = PIN_DESC(C, 4, BOARD_AF_NONE),

    [BOARD_PIN_SPI1_NSS] = PIN_DESC(G, 5, BOARD_AF_NONE),
    [BOARD_PIN_SPI1_SCK] = PIN_DESC(G, 2, BOARD_AF_NONE),
    [BOARD_PIN_SPI1_MISO] = PIN_DESC(G, 3, BOARD_AF_NONE),
    [BOARD_PIN_SPI1_MOSI] = PIN_DESC(G, 4, BOARD_AF_NONE),

    [BOARD_PIN_SPI3_NSS] = PIN_DESC(G, 12, BOARD_AF_NONE),
    [BOARD_PIN_SPI3_SCK] = PIN_DESC(G, 9, BOARD_AF_NONE),
    [BOARD_PIN_SPI3_MISO] = PIN_DESC(G, 10, BOARD_AF_NONE),
    [BOARD_PIN_SPI3_MOSI] = PIN_DESC(G, 11, BOARD_AF_NONE),

    [BOARD_PIN_I2C1_SCL] = PIN_DESC(B, 6, BOARD_AF_NONE),
    [BOARD_PIN_I2C1_SDA] = PIN_DESC(B, 7, BOARD_AF_NONE),

    [BOARD_PIN_I2C2_SCL] = PIN_DESC(B, 10, BOARD_AF_NONE),
    [BOARD_PIN_I2C2_SDA] = PIN_DESC(B, 14, BOARD_AF_NONE),

    [BOARD_PIN_I2C3_SCL] = PIN_DESC(A, 7, BOARD_AF_NONE),
    [BOARD_PIN_I2C3_SDA] = PIN_DESC(B, 4, BOARD_AF_NONE),

    [BOARD_PIN_USB_DM] = PIN_DESC(A, 11, BOARD_AF_NONE),
    [BOARD_PIN_USB_DP] = PIN_DESC(A, 12, BOARD_AF_NONE),

    [BOARD_PIN_CAN1_RX] = PIN_DESC(B, 8, 9U),
    [BOARD_PIN_CAN1_TX] = PIN_DESC(B, 9, 9U),
    [BOARD_PIN_CAN2_RX] = PIN_DESC(B, 12, 10U),
    [BOARD_PIN_CAN2_TX] = PIN_DESC(B, 13, 10U),

    [BOARD_PIN_RTC_OUT] = PIN_DESC(B, 2, 0U),
    [BOARD_PIN_ADC12_IN5] = PIN_DESC(A, 0, BOARD_AF_NONE),

    [BOARD_PIN_USART2_RX] = PIN_DESC(A, 15, BOARD_AF_NONE),
    [BOARD_PIN_USART2_TX] = PIN_DESC(A, 2, BOARD_AF_NONE),

    [BOARD_PIN_PED_REG_DATA0] = PIN_DESC(D, 0, BOARD_AF_NONE),
    [BOARD_PIN_PED_REG_DATA1] = PIN_DESC(D, 1, BOARD_AF_NONE),
    [BOARD_PIN_PED_REG_DATA2] = PIN_DESC(D, 2, BOARD_AF_NONE),
    [BOARD_PIN_PED_REG_DATA3] = PIN_DESC(D, 3, BOARD_AF_NONE),
    [BOARD_PIN_PED_REG_DATA4] = PIN_DESC(D, 4, BOARD_AF_NONE),
    [BOARD_PIN_PED_REG_DATA5] = PIN_DESC(D, 5, BOARD_AF_NONE),
    [BOARD_PIN_PED_REG_DATA6] = PIN_DESC(D, 6, BOARD_AF_NONE),
    [BOARD_PIN_PED_REG_DATA7] = PIN_DESC(D, 7, BOARD_AF_NONE),
    [BOARD_PIN_PED_REG_DATA8] = PIN_DESC(D, 8, BOARD_AF_NONE),
    [BOARD_PIN_PED_REG_DATA9] = PIN_DESC(D, 9, BOARD_AF_NONE),
    [BOARD_PIN_PED_REG_DATA10] = PIN_DESC(D, 10, BOARD_AF_NONE),
    [BOARD_PIN_PED_REG_DATA11] = PIN_DESC(D, 11, BOARD_AF_NONE),
    [BOARD_PIN_PED_REG_DATA12] = PIN_DESC(D, 12, BOARD_AF_NONE),
    [BOARD_PIN_PED_REG_DATA13] = PIN_DESC(D, 13, BOARD_AF_NONE),
    [BOARD_PIN_PED_REG_DATA14] = PIN_DESC(D, 14, BOARD_AF_NONE),
    [BOARD_PIN_PED_REG_DATA15] = PIN_DESC(D, 15, BOARD_AF_NONE),

    [BOARD_PIN_PED_REG_ADDR0] = PIN_DESC(F, 0, BOARD_AF_NONE),
    [BOARD_PIN_PED_REG_ADDR1] = PIN_DESC(F, 1, BOARD_AF_NONE),
    [BOARD_PIN_PED_REG_ADDR2] = PIN_DESC(F, 2, BOARD_AF_NONE),
    [BOARD_PIN_PED_REG_ADDR3] = PIN_DESC(F, 3, BOARD_AF_NONE),
    [BOARD_PIN_PED_REG_ADDR4] = PIN_DESC(F, 4, BOARD_AF_NONE),
    [BOARD_PIN_PED_REG_ADDR5] = PIN_DESC(F, 5, BOARD_AF_NONE),
    [BOARD_PIN_PED_REG_ADDR6] = PIN_DESC(F, 6, BOARD_AF_NONE),
    [BOARD_PIN_PED_REG_ADDR7] = PIN_DESC(F, 7, BOARD_AF_NONE),

    [BOARD_PIN_PED_REG_DIR] = PIN_DESC(F, 8, BOARD_AF_NONE),
    [BOARD_PIN_PED_REG_WRCLK] = PIN_DESC(F, 9, BOARD_AF_NONE),
    [BOARD_PIN_PED_REG_READY] = PIN_DESC(G, 0, BOARD_AF_NONE),

    [BOARD_PIN_PU_CAN1_SHDN] = PIN_DESC(E, 0, BOARD_AF_NONE),
    [BOARD_PIN_PU_CAN1_S] = PIN_DESC(E, 1, BOARD_AF_NONE),
    [BOARD_PIN_PU_CAN2_SHDN] = PIN_DESC(E, 2, BOARD_AF_NONE),
    [BOARD_PIN_PU_CAN2_S] = PIN_DESC(E, 3, BOARD_AF_NONE),

    [BOARD_PIN_PU_NAND1_PS] = PIN_DESC(E, 4, BOARD_AF_NONE),
    [BOARD_PIN_PU_NAND1_PSON] = PIN_DESC(G, 1, BOARD_AF_NONE),
    [BOARD_PIN_PU_NAND2_PS] = PIN_DESC(E, 5, BOARD_AF_NONE),
    [BOARD_PIN_PU_NAND2_PSON] = PIN_DESC(G, 6, BOARD_AF_NONE),

    [BOARD_PIN_PU_PED_PS] = PIN_DESC(E, 6, BOARD_AF_NONE),
    [BOARD_PIN_PU_USB_VBUS] = PIN_DESC(A, 9, BOARD_AF_NONE),

    [BOARD_PIN_PED_TG] = PIN_DESC(G, 13, BOARD_AF_NONE),
    [BOARD_PIN_PED_TGRES] = PIN_DESC(E, 7, BOARD_AF_NONE),
    [BOARD_PIN_PED_INHIBIT] = PIN_DESC(E, 8, BOARD_AF_NONE),
    [BOARD_PIN_PED_SLEEP] = PIN_DESC(E, 9, BOARD_AF_NONE),
    [BOARD_PIN_PED_PSON] = PIN_DESC(G, 14, BOARD_AF_NONE),

    [BOARD_PIN_DEBUG_UART_TX] = PIN_DESC(G, 7, 8U),
    [BOARD_PIN_DEBUG_UART_RX] = PIN_DESC(G, 8, 8U),
};

const BoardPinDesc* board_pin_get(BoardPinId id) {
    if ((uint32_t)id >= (uint32_t)BOARD_PIN_COUNT) {
        return 0;
    }

    return &board_pins[id];
}
