#ifndef NATALIA_CORE_STATUS_H
#define NATALIA_CORE_STATUS_H

typedef enum {
    BOARD_OK = 0,
    BOARD_ERR_INVALID_ARG,
    BOARD_ERR_TIMEOUT,
    BOARD_ERR_IO,
    BOARD_ERR_CRC,
    BOARD_ERR_BUSY,
    BOARD_ERR_NOT_READY,
    BOARD_ERR_UNSUPPORTED
} BoardStatus;

#endif /* NATALIA_CORE_STATUS_H */