#ifndef NATALIA_CORE_TEST_MODE_CONFIG_H
#define NATALIA_CORE_TEST_MODE_CONFIG_H

#include <stdint.h>

#define TEST_MODE_PACKET_SIZE 2048U
#define TEST_MODE_BLOCK_COUNT 2048U
#define TEST_MODE_PACKETS_PER_BLOCK 128U
#define TEST_MODE_NERR_ELEMENT_BYTES 3U
#define TEST_MODE_NERR_BYTE_SIZE (TEST_MODE_BLOCK_COUNT * TEST_MODE_NERR_ELEMENT_BYTES)
#define TEST_MODE_NERR_MAX 0x00FFFFFFUL

#define TEST_RESULT_STATUS_OK 0UL
#define TEST_RESULT_STATUS_COMPARE_MISMATCH (1UL << 0)
#define TEST_RESULT_STATUS_NAND_WRITE_ERROR (1UL << 1)
#define TEST_RESULT_STATUS_NAND_READ_ERROR (1UL << 2)
#define TEST_RESULT_STATUS_NAND_ERASE_ERROR (1UL << 3)

#define TEST_MODE_FAILED_ADDRESS_NONE UINT32_MAX

#endif