#ifndef NATALIA_CORE_TEST_MODE_CONFIG_H
#define NATALIA_CORE_TEST_MODE_CONFIG_H

#include <stdint.h>

#define TEST_MODE_BLOCK_SIZE 256U
#define TEST_MODE_BLOCK_COUNT 16U

#define TEST_RESULT_STATUS_OK 0UL
#define TEST_RESULT_STATUS_COMPARE_MISMATCH (1UL << 0)
#define TEST_RESULT_STATUS_NAND_WRITE_ERROR (1UL << 1)
#define TEST_RESULT_STATUS_NAND_READ_ERROR (1UL << 2)

#define TEST_MODE_FAILED_ADDRESS_NONE UINT32_MAX

#endif // NATALIA_CORE_TEST_MODE_CONFIG_H
